name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install build tools
      run: |
        npm install -g @vercel/ncc
        npm install -g pkg
      
    - name: Build executable
      run: npm run build
      
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: csfloat-executable
        path: build/csfloat.exe
        
    - name: Upload README
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: README.md